"""Seed data for the Geekverse tools website."""

SEED_CATEGORIES = [
    {
        "id": "cat-dev",
        "slug": "dev",
        "name": "Dev Tools",
        "color": "#3b82f6",
        "description": "Code editors, version control, runtimes & IDEs",
    },
    {
        "id": "cat-network",
        "slug": "network",
        "name": "Networking",
        "color": "#06b6d4",
        "description": "Packet sniffers, SSH clients, scanners & VPNs",
    },
    {
        "id": "cat-security",
        "slug": "security",
        "name": "Cybersecurity",
        "color": "#ef4444",
        "description": "Pentesting, encryption, password managers & anti-malware",
    },
    {
        "id": "cat-os",
        "slug": "os",
        "name": "OS Utilities",
        "color": "#10b981",
        "description": "Power tools, archivers, automation & system tweaks",
    },
    {
        "id": "cat-ai",
        "slug": "ai",
        "name": "AI & ML",
        "color": "#a855f7",
        "description": "Local LLMs, model runners, generative AI tooling",
    },
    {
        "id": "cat-media",
        "slug": "media",
        "name": "File & Media",
        "color": "#f59e0b",
        "description": "Audio, video, image editors & file conversion",
    },
    {
        "id": "cat-hardware",
        "slug": "hardware",
        "name": "Hardware",
        "color": "#f97316",
        "description": "Monitoring, benchmarking & system info",
    },
    {
        "id": "cat-fun",
        "slug": "fun",
        "name": "Fun & Useless",
        "color": "#ec4899",
        "description": "Silly, absurd, meditative or weirdly addictive web toys",
    },
]


SEED_TOOLS = [
    # ---------------- DEV ----------------
    {
        "name": "Visual Studio Code",
        "category_slug": "dev",
        "description": "The most-used code editor on the planet. Extensible, fast, free.",
        "alternative_uses": ["Markdown editing", "Remote SSH dev", "Jupyter notebooks", "Git GUI"],
        "download_url": "https://code.visualstudio.com/Download",
        "homepage_url": "https://code.visualstudio.com/",
        "icon": "Code2",
        "popularity": 99,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Sublime Text",
        "category_slug": "dev",
        "description": "Buttery-fast native text editor with legendary multi-cursor support.",
        "alternative_uses": ["Note taking", "Log file viewing", "Quick scripting"],
        "download_url": "https://www.sublimetext.com/download",
        "homepage_url": "https://www.sublimetext.com/",
        "icon": "FileCode",
        "popularity": 78,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Notepad++",
        "category_slug": "dev",
        "description": "Lightweight Windows text editor with syntax highlighting for 80+ languages.",
        "alternative_uses": ["Log analysis", "Hex editing", "Diff comparison"],
        "download_url": "https://notepad-plus-plus.org/downloads/",
        "homepage_url": "https://notepad-plus-plus.org/",
        "icon": "FileText",
        "popularity": 82,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "Git",
        "category_slug": "dev",
        "description": "The distributed version control system that runs the software world.",
        "alternative_uses": ["Backup snapshots", "Config file tracking", "Writing project history"],
        "download_url": "https://git-scm.com/downloads",
        "homepage_url": "https://git-scm.com/",
        "icon": "GitBranch",
        "popularity": 100,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Docker Desktop",
        "category_slug": "dev",
        "description": "Run, build and ship containerized apps anywhere with one click.",
        "alternative_uses": ["Local databases", "Reproducible CI", "Sandbox malware analysis"],
        "download_url": "https://www.docker.com/products/docker-desktop/",
        "homepage_url": "https://www.docker.com/",
        "icon": "Container",
        "popularity": 95,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Postman",
        "category_slug": "dev",
        "description": "The de-facto tool for testing, documenting and mocking APIs.",
        "alternative_uses": ["Load testing", "OAuth flow debugging", "Webhook inspection"],
        "download_url": "https://www.postman.com/downloads/",
        "homepage_url": "https://www.postman.com/",
        "icon": "Send",
        "popularity": 90,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "JetBrains Toolbox",
        "category_slug": "dev",
        "description": "Manage every JetBrains IDE (IntelliJ, PyCharm, WebStorm, etc) from one app.",
        "alternative_uses": ["Side-by-side versions", "EAP testing", "License management"],
        "download_url": "https://www.jetbrains.com/toolbox-app/",
        "homepage_url": "https://www.jetbrains.com/",
        "icon": "Boxes",
        "popularity": 80,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "DBeaver",
        "category_slug": "dev",
        "description": "Universal database GUI: works with Postgres, MySQL, Mongo, Redis, you name it.",
        "alternative_uses": ["Schema visualization", "Data export", "ER diagrams"],
        "download_url": "https://dbeaver.io/download/",
        "homepage_url": "https://dbeaver.io/",
        "icon": "Database",
        "popularity": 76,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Node.js",
        "category_slug": "dev",
        "description": "JavaScript runtime that powers most modern backends, CLIs and toolchains.",
        "alternative_uses": ["Quick HTTP servers", "Build tooling", "Scripting"],
        "download_url": "https://nodejs.org/en/download",
        "homepage_url": "https://nodejs.org/",
        "icon": "Hexagon",
        "popularity": 96,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Python",
        "category_slug": "dev",
        "description": "Batteries-included language used for AI, web, scripting, science, everything.",
        "alternative_uses": ["Automation", "Data analysis", "Game scripting", "Glue code"],
        "download_url": "https://www.python.org/downloads/",
        "homepage_url": "https://www.python.org/",
        "icon": "Code",
        "popularity": 98,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Insomnia",
        "category_slug": "dev",
        "description": "Sleek, open-source REST/GraphQL/gRPC client with a beautiful UI.",
        "alternative_uses": ["API design", "Environment variable testing", "Plugin scripting"],
        "download_url": "https://insomnia.rest/download",
        "homepage_url": "https://insomnia.rest/",
        "icon": "Moon",
        "popularity": 72,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "RegExr",
        "category_slug": "dev",
        "description": "Interactive regex playground with cheatsheet and shared patterns.",
        "alternative_uses": ["Learning regex", "Text mining", "Validation prototyping"],
        "download_url": "https://regexr.com/",
        "homepage_url": "https://regexr.com/",
        "icon": "Regex",
        "popularity": 70,
        "is_open_source": True,
        "platforms": ["Web"],
    },

    # ---------------- NETWORK ----------------
    {
        "name": "Wireshark",
        "category_slug": "network",
        "description": "The world's foremost network protocol analyzer. See every packet.",
        "alternative_uses": ["Learning TCP/IP", "Detecting suspicious traffic", "VoIP debugging"],
        "download_url": "https://www.wireshark.org/download.html",
        "homepage_url": "https://www.wireshark.org/",
        "icon": "Activity",
        "popularity": 92,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Nmap",
        "category_slug": "network",
        "description": "Network scanner & host discovery used by every sysadmin and pentester.",
        "alternative_uses": ["Inventory scanning", "Security audits", "Service fingerprinting"],
        "download_url": "https://nmap.org/download.html",
        "homepage_url": "https://nmap.org/",
        "icon": "Radar",
        "popularity": 88,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "PuTTY",
        "category_slug": "network",
        "description": "Tiny, legendary SSH/Telnet client for Windows. It just works.",
        "alternative_uses": ["Serial console", "SSH tunneling", "Key generation (PuTTYgen)"],
        "download_url": "https://www.putty.org/",
        "homepage_url": "https://www.chiark.greenend.org.uk/~sgtatham/putty/",
        "icon": "Terminal",
        "popularity": 85,
        "is_open_source": True,
        "platforms": ["Windows", "Linux"],
    },
    {
        "name": "WinSCP",
        "category_slug": "network",
        "description": "Drag-and-drop SFTP / SCP / FTP client with a powerful synchronization mode.",
        "alternative_uses": ["Server backups", "Remote editing", "Scripted uploads"],
        "download_url": "https://winscp.net/eng/download.php",
        "homepage_url": "https://winscp.net/",
        "icon": "ArrowLeftRight",
        "popularity": 74,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "Angry IP Scanner",
        "category_slug": "network",
        "description": "Fast, friendly IP and port scanner. Cross-platform and free.",
        "alternative_uses": ["LAN discovery", "Finding rogue devices", "Open port audits"],
        "download_url": "https://angryip.org/download/",
        "homepage_url": "https://angryip.org/",
        "icon": "Wifi",
        "popularity": 68,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "OpenVPN",
        "category_slug": "network",
        "description": "Battle-tested open-source VPN, the standard for self-hosted tunnels.",
        "alternative_uses": ["Site-to-site links", "Remote work access", "Geo-bypass"],
        "download_url": "https://openvpn.net/community-downloads/",
        "homepage_url": "https://openvpn.net/",
        "icon": "Shield",
        "popularity": 78,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Cloudflare WARP",
        "category_slug": "network",
        "description": "Fast, privacy-friendly DNS+VPN client powered by 1.1.1.1.",
        "alternative_uses": ["Bypass ISP throttling", "Encrypt mobile traffic", "DNS over HTTPS"],
        "download_url": "https://1.1.1.1/",
        "homepage_url": "https://1.1.1.1/",
        "icon": "Cloud",
        "popularity": 71,
        "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"],
    },

    # ---------------- SECURITY ----------------
    {
        "name": "Kali Linux",
        "category_slug": "security",
        "description": "A Debian-based distro packed with 600+ pentesting and forensics tools.",
        "alternative_uses": ["CTF practice", "Red team labs", "Forensic recovery"],
        "download_url": "https://www.kali.org/get-kali/",
        "homepage_url": "https://www.kali.org/",
        "icon": "Skull",
        "popularity": 89,
        "is_open_source": True,
        "platforms": ["Linux", "VM", "WSL"],
    },
    {
        "name": "Metasploit Framework",
        "category_slug": "security",
        "description": "The world's most used penetration-testing framework.",
        "alternative_uses": ["Exploit development", "Vulnerability research", "Training labs"],
        "download_url": "https://www.metasploit.com/download",
        "homepage_url": "https://www.metasploit.com/",
        "icon": "Bug",
        "popularity": 81,
        "is_open_source": True,
        "platforms": ["Windows", "Linux"],
    },
    {
        "name": "Burp Suite Community",
        "category_slug": "security",
        "description": "Industry-standard web app security testing proxy.",
        "alternative_uses": ["API hacking", "Bug bounty hunting", "Request replay"],
        "download_url": "https://portswigger.net/burp/communitydownload",
        "homepage_url": "https://portswigger.net/burp",
        "icon": "Crosshair",
        "popularity": 84,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "KeePassXC",
        "category_slug": "security",
        "description": "Offline, open-source password manager. Your data, your vault.",
        "alternative_uses": ["TOTP storage", "Secure notes", "SSH key passphrases"],
        "download_url": "https://keepassxc.org/download/",
        "homepage_url": "https://keepassxc.org/",
        "icon": "KeyRound",
        "popularity": 75,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "VeraCrypt",
        "category_slug": "security",
        "description": "Fork of TrueCrypt. Creates encrypted containers and full-disk volumes.",
        "alternative_uses": ["Encrypt USB sticks", "Hidden volumes", "Backups"],
        "download_url": "https://www.veracrypt.fr/en/Downloads.html",
        "homepage_url": "https://www.veracrypt.fr/",
        "icon": "Lock",
        "popularity": 70,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Tor Browser",
        "category_slug": "security",
        "description": "Browse the web anonymously through the Tor onion routing network.",
        "alternative_uses": ["Whistleblowing", "Censorship bypass", "Onion service hosting"],
        "download_url": "https://www.torproject.org/download/",
        "homepage_url": "https://www.torproject.org/",
        "icon": "EyeOff",
        "popularity": 82,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Bitwarden",
        "category_slug": "security",
        "description": "Open-source password manager that syncs across every device.",
        "alternative_uses": ["Secure sharing", "Self-hosted vaults", "2FA codes"],
        "download_url": "https://bitwarden.com/download/",
        "homepage_url": "https://bitwarden.com/",
        "icon": "Vault",
        "popularity": 87,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"],
    },
    {
        "name": "Malwarebytes",
        "category_slug": "security",
        "description": "Specialist anti-malware for cleaning what antivirus misses.",
        "alternative_uses": ["Adware removal", "Ransomware protection", "Browser hijack cleanup"],
        "download_url": "https://www.malwarebytes.com/mwb-download",
        "homepage_url": "https://www.malwarebytes.com/",
        "icon": "ShieldAlert",
        "popularity": 73,
        "platforms": ["Windows", "macOS"],
    },

    # ---------------- OS ----------------
    {
        "name": "Microsoft PowerToys",
        "category_slug": "os",
        "description": "Power-user utilities for Windows: FancyZones, PowerRename, Color Picker, more.",
        "alternative_uses": ["Window snapping", "Bulk renaming", "Mouse highlighter"],
        "download_url": "https://github.com/microsoft/PowerToys/releases",
        "homepage_url": "https://learn.microsoft.com/en-us/windows/powertoys/",
        "icon": "Wand2",
        "popularity": 91,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "7-Zip",
        "category_slug": "os",
        "description": "Free open-source archiver with industry-leading 7z compression ratio.",
        "alternative_uses": ["Encrypted archives", "Splitting files", "ISO extraction"],
        "download_url": "https://www.7-zip.org/download.html",
        "homepage_url": "https://www.7-zip.org/",
        "icon": "Archive",
        "popularity": 94,
        "is_open_source": True,
        "platforms": ["Windows", "Linux"],
    },
    {
        "name": "Rufus",
        "category_slug": "os",
        "description": "Tiny utility to create bootable USB drives from ISO files. Fast.",
        "alternative_uses": ["Live USB", "BIOS updates", "OS installers"],
        "download_url": "https://rufus.ie/",
        "homepage_url": "https://rufus.ie/",
        "icon": "Usb",
        "popularity": 86,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "Ventoy",
        "category_slug": "os",
        "description": "Flash one USB once, drop in any number of ISOs, boot any of them.",
        "alternative_uses": ["Multi-distro testing", "Recovery toolkit", "WIM/IMG support"],
        "download_url": "https://www.ventoy.net/en/download.html",
        "homepage_url": "https://www.ventoy.net/",
        "icon": "HardDriveDownload",
        "popularity": 80,
        "is_open_source": True,
        "platforms": ["Windows", "Linux"],
    },
    {
        "name": "Everything Search",
        "category_slug": "os",
        "description": "Instantly find any file on your NTFS drives — by name, in milliseconds.",
        "alternative_uses": ["Disk cleanup", "Finding duplicates", "Folder size queries"],
        "download_url": "https://www.voidtools.com/downloads/",
        "homepage_url": "https://www.voidtools.com/",
        "icon": "Search",
        "popularity": 83,
        "platforms": ["Windows"],
    },
    {
        "name": "AutoHotkey",
        "category_slug": "os",
        "description": "Scriptable automation for Windows. Remap keys, build macros, automate anything.",
        "alternative_uses": ["Hotkeys", "Auto-clickers", "GUI bots"],
        "download_url": "https://www.autohotkey.com/download/",
        "homepage_url": "https://www.autohotkey.com/",
        "icon": "Keyboard",
        "popularity": 77,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "Sysinternals Suite",
        "category_slug": "os",
        "description": "Mark Russinovich's legendary toolbox: Process Explorer, Autoruns, TCPView…",
        "alternative_uses": ["Malware analysis", "System debugging", "Startup cleanup"],
        "download_url": "https://learn.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite",
        "homepage_url": "https://learn.microsoft.com/en-us/sysinternals/",
        "icon": "Cog",
        "popularity": 88,
        "platforms": ["Windows"],
    },
    {
        "name": "Process Hacker",
        "category_slug": "os",
        "description": "Open-source Task Manager replacement on steroids.",
        "alternative_uses": ["Detecting handles", "DLL inspection", "Stopping stubborn processes"],
        "download_url": "https://processhacker.sourceforge.io/downloads.php",
        "homepage_url": "https://processhacker.sourceforge.io/",
        "icon": "Cpu",
        "popularity": 65,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "Oh My Zsh",
        "category_slug": "os",
        "description": "Community framework for managing your Zsh shell config. Themes & plugins galore.",
        "alternative_uses": ["Prompt customization", "Auto-suggestions", "Git aliases"],
        "download_url": "https://ohmyz.sh/",
        "homepage_url": "https://ohmyz.sh/",
        "icon": "TerminalSquare",
        "popularity": 79,
        "is_open_source": True,
        "platforms": ["macOS", "Linux", "WSL"],
    },

    # ---------------- AI ----------------
    {
        "name": "Ollama",
        "category_slug": "ai",
        "description": "Run Llama, Mistral, Phi, DeepSeek and more locally with a single command.",
        "alternative_uses": ["Private chat", "RAG dev", "Offline coding assistant"],
        "download_url": "https://ollama.com/download",
        "homepage_url": "https://ollama.com/",
        "icon": "Bot",
        "popularity": 90,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "LM Studio",
        "category_slug": "ai",
        "description": "Beautiful desktop UI to download and chat with local LLMs (GGUF, MLX).",
        "alternative_uses": ["Model comparison", "Local API server", "Prompt experiments"],
        "download_url": "https://lmstudio.ai/",
        "homepage_url": "https://lmstudio.ai/",
        "icon": "MessageSquare",
        "popularity": 84,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Cursor",
        "category_slug": "ai",
        "description": "AI-first IDE built on VS Code. Refactor, chat with codebase, generate fast.",
        "alternative_uses": ["Pair programming", "Code review", "Doc writing"],
        "download_url": "https://www.cursor.com/",
        "homepage_url": "https://www.cursor.com/",
        "icon": "Sparkles",
        "popularity": 92,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Stable Diffusion WebUI",
        "category_slug": "ai",
        "description": "AUTOMATIC1111's web UI to run Stable Diffusion locally with thousands of extensions.",
        "alternative_uses": ["Inpainting", "ControlNet", "LoRA training"],
        "download_url": "https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases",
        "homepage_url": "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
        "icon": "ImagePlus",
        "popularity": 85,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "ComfyUI",
        "category_slug": "ai",
        "description": "Powerful node-based GUI for Stable Diffusion. Build pipelines visually.",
        "alternative_uses": ["Video generation", "Custom workflows", "Batch jobs"],
        "download_url": "https://github.com/comfyanonymous/ComfyUI/releases",
        "homepage_url": "https://github.com/comfyanonymous/ComfyUI",
        "icon": "Network",
        "popularity": 80,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Anaconda",
        "category_slug": "ai",
        "description": "All-in-one Python distribution with conda, Jupyter and 250+ data-science packages.",
        "alternative_uses": ["Env management", "ML prototyping", "Teaching Python"],
        "download_url": "https://www.anaconda.com/download",
        "homepage_url": "https://www.anaconda.com/",
        "icon": "FlaskConical",
        "popularity": 78,
        "platforms": ["Windows", "macOS", "Linux"],
    },

    # ---------------- MEDIA ----------------
    {
        "name": "VLC Media Player",
        "category_slug": "media",
        "description": "Plays literally everything. The Swiss army knife of media players.",
        "alternative_uses": ["Stream conversion", "Disc ripping", "Screen recording"],
        "download_url": "https://www.videolan.org/vlc/",
        "homepage_url": "https://www.videolan.org/",
        "icon": "Play",
        "popularity": 97,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux", "iOS", "Android"],
    },
    {
        "name": "OBS Studio",
        "category_slug": "media",
        "description": "Free, open-source screen recorder and live streaming software.",
        "alternative_uses": ["Twitch streaming", "Tutorial recording", "Webcam virtual cam"],
        "download_url": "https://obsproject.com/download",
        "homepage_url": "https://obsproject.com/",
        "icon": "Video",
        "popularity": 89,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "HandBrake",
        "category_slug": "media",
        "description": "Open-source video transcoder. Converts almost any format into MP4/MKV.",
        "alternative_uses": ["Shrinking files", "Mobile-optimised exports", "DVD ripping"],
        "download_url": "https://handbrake.fr/downloads.php",
        "homepage_url": "https://handbrake.fr/",
        "icon": "FastForward",
        "popularity": 75,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Audacity",
        "category_slug": "media",
        "description": "Multi-track audio editor and recorder. Free & open source for 20+ years.",
        "alternative_uses": ["Podcast editing", "Noise removal", "Vinyl digitisation"],
        "download_url": "https://www.audacityteam.org/download/",
        "homepage_url": "https://www.audacityteam.org/",
        "icon": "AudioLines",
        "popularity": 82,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "GIMP",
        "category_slug": "media",
        "description": "The GNU Image Manipulation Program — a free Photoshop alternative.",
        "alternative_uses": ["Photo editing", "Icon design", "Batch processing"],
        "download_url": "https://www.gimp.org/downloads/",
        "homepage_url": "https://www.gimp.org/",
        "icon": "Brush",
        "popularity": 84,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Krita",
        "category_slug": "media",
        "description": "Professional digital painting and illustration app loved by concept artists.",
        "alternative_uses": ["Animation", "Comic creation", "Texture painting"],
        "download_url": "https://krita.org/en/download/",
        "homepage_url": "https://krita.org/",
        "icon": "Palette",
        "popularity": 76,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "FFmpeg",
        "category_slug": "media",
        "description": "The command-line tool that secretly powers half the internet's media pipelines.",
        "alternative_uses": ["Scripted conversions", "Streaming", "Filter graphs"],
        "download_url": "https://ffmpeg.org/download.html",
        "homepage_url": "https://ffmpeg.org/",
        "icon": "Film",
        "popularity": 93,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Inkscape",
        "category_slug": "media",
        "description": "Powerful, free SVG vector graphics editor.",
        "alternative_uses": ["Logo design", "Cricut/laser cutting", "Map making"],
        "download_url": "https://inkscape.org/release/",
        "homepage_url": "https://inkscape.org/",
        "icon": "PenTool",
        "popularity": 74,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },
    {
        "name": "Blender",
        "category_slug": "media",
        "description": "Free 3D creation suite: modeling, sculpting, animation, VFX and even video editing.",
        "alternative_uses": ["3D printing", "Game asset creation", "Architectural viz"],
        "download_url": "https://www.blender.org/download/",
        "homepage_url": "https://www.blender.org/",
        "icon": "Box",
        "popularity": 91,
        "is_open_source": True,
        "platforms": ["Windows", "macOS", "Linux"],
    },

    # ---------------- HARDWARE ----------------
    {
        "name": "CPU-Z",
        "category_slug": "hardware",
        "description": "Tells you exactly what's inside your PC: CPU, RAM, motherboard, GPU.",
        "alternative_uses": ["Overclocking", "Verifying parts", "Stress tests"],
        "download_url": "https://www.cpuid.com/softwares/cpu-z.html",
        "homepage_url": "https://www.cpuid.com/",
        "icon": "Cpu",
        "popularity": 85,
        "platforms": ["Windows"],
    },
    {
        "name": "HWMonitor",
        "category_slug": "hardware",
        "description": "Real-time temperatures, voltages and fan speeds for every sensor in your rig.",
        "alternative_uses": ["Thermal debugging", "Logging", "OC verification"],
        "download_url": "https://www.cpuid.com/softwares/hwmonitor.html",
        "homepage_url": "https://www.cpuid.com/",
        "icon": "Thermometer",
        "popularity": 78,
        "platforms": ["Windows"],
    },
    {
        "name": "CrystalDiskInfo",
        "category_slug": "hardware",
        "description": "Check the SMART health of your hard drives & SSDs before they die on you.",
        "alternative_uses": ["Used drive shopping", "Predictive failure", "TBW tracking"],
        "download_url": "https://crystalmark.info/en/download/",
        "homepage_url": "https://crystalmark.info/",
        "icon": "HardDrive",
        "popularity": 72,
        "is_open_source": True,
        "platforms": ["Windows"],
    },
    {
        "name": "MSI Afterburner",
        "category_slug": "hardware",
        "description": "The GPU tweaker. Overclock, undervolt, monitor and benchmark any card.",
        "alternative_uses": ["Fan curves", "On-screen FPS", "Recording gameplay"],
        "download_url": "https://www.msi.com/Landing/afterburner/graphics-cards",
        "homepage_url": "https://www.msi.com/",
        "icon": "Gauge",
        "popularity": 87,
        "platforms": ["Windows"],
    },
    {
        "name": "GPU-Z",
        "category_slug": "hardware",
        "description": "Tiny utility that shows everything about your graphics card. From TechPowerUp.",
        "alternative_uses": ["Buying second-hand GPUs", "Verifying BIOS", "Sensor logging"],
        "download_url": "https://www.techpowerup.com/gpuz/",
        "homepage_url": "https://www.techpowerup.com/",
        "icon": "MonitorCog",
        "popularity": 76,
        "platforms": ["Windows"],
    },
    {
        "name": "Speccy",
        "category_slug": "hardware",
        "description": "Clean, friendly system info app. Great for non-technical family tech support.",
        "alternative_uses": ["Inventory exports", "Old hardware audits", "Quick diagnostics"],
        "download_url": "https://www.ccleaner.com/speccy/download",
        "homepage_url": "https://www.ccleaner.com/speccy",
        "icon": "Info",
        "popularity": 60,
        "platforms": ["Windows"],
    },

    # ---------------- FUN ----------------
    {
        "name": "Cookie Clicker",
        "category_slug": "fun",
        "description": "Bake cookies. Buy grandmas. Ascend. The original idle game.",
        "alternative_uses": ["Wasting hours", "Tab-background meditation", "Studying RNG"],
        "download_url": "https://orteil.dashnet.org/cookieclicker/",
        "homepage_url": "https://orteil.dashnet.org/cookieclicker/",
        "icon": "Cookie",
        "popularity": 88,
        "platforms": ["Web"],
    },
    {
        "name": "Hacker Typer",
        "category_slug": "fun",
        "description": "Mash random keys, look like an elite hacker in green text on black. Classic.",
        "alternative_uses": ["Pranks", "Movie props", "Stress relief"],
        "download_url": "https://hackertyper.net/",
        "homepage_url": "https://hackertyper.net/",
        "icon": "TerminalSquare",
        "popularity": 71,
        "platforms": ["Web"],
    },
    {
        "name": "GeoFS",
        "category_slug": "fun",
        "description": "Free in-browser flight simulator using real satellite imagery. Just take off.",
        "alternative_uses": ["Procrastination", "Geography learning", "Multiplayer hangouts"],
        "download_url": "https://www.geo-fs.com/",
        "homepage_url": "https://www.geo-fs.com/",
        "icon": "Plane",
        "popularity": 64,
        "platforms": ["Web"],
    },
    {
        "name": "ASCII Art Generator (patorjk)",
        "category_slug": "fun",
        "description": "Type anything, pick a font, get instant ASCII art for your README / banner.",
        "alternative_uses": ["MOTD banners", "Email signatures", "Boredom"],
        "download_url": "https://patorjk.com/software/taag/",
        "homepage_url": "https://patorjk.com/",
        "icon": "Type",
        "popularity": 66,
        "platforms": ["Web"],
    },
    {
        "name": "The Useless Web",
        "category_slug": "fun",
        "description": "Hit a button. Be teleported to the weirdest corner of the internet.",
        "alternative_uses": ["Procrastination", "Mood booster", "Conversation starter"],
        "download_url": "https://theuselessweb.com/",
        "homepage_url": "https://theuselessweb.com/",
        "icon": "Shuffle",
        "popularity": 73,
        "platforms": ["Web"],
    },
    {
        "name": "Pointer Pointer",
        "category_slug": "fun",
        "description": "Move your mouse. Strangers will point at it. That's it. That's the site.",
        "alternative_uses": ["Existential crises", "Demo for friends", "Background art"],
        "download_url": "https://pointerpointer.com/",
        "homepage_url": "https://pointerpointer.com/",
        "icon": "MousePointer2",
        "popularity": 58,
        "platforms": ["Web"],
    },
    {
        "name": "Sandspiel",
        "category_slug": "fun",
        "description": "Mesmerizing falling-sand sandbox. Mix water, fire, plants, lava and watch.",
        "alternative_uses": ["Stress relief", "Teaching cellular automata", "Pixel art"],
        "download_url": "https://sandspiel.club/",
        "homepage_url": "https://sandspiel.club/",
        "icon": "Sparkle",
        "popularity": 62,
        "platforms": ["Web"],
    },
    {
        "name": "WindowSwap",
        "category_slug": "fun",
        "description": "Look out of someone else's window from somewhere in the world. Surprisingly calming.",
        "alternative_uses": ["Travel daydreaming", "Meditation", "Writing inspiration"],
        "download_url": "https://www.window-swap.com/",
        "homepage_url": "https://www.window-swap.com/",
        "icon": "Globe",
        "popularity": 55,
        "platforms": ["Web"],
    },
    {
        "name": "Bongo Cat",
        "category_slug": "fun",
        "description": "A cat that drums along to your keypresses. Inexplicably joyful.",
        "alternative_uses": ["Stream overlay", "ASMR", "Typing motivation"],
        "download_url": "https://bongo.cat/",
        "homepage_url": "https://bongo.cat/",
        "icon": "Cat",
        "popularity": 67,
        "platforms": ["Web"],
    },
    {
        "name": "neal.fun",
        "category_slug": "fun",
        "description": "A whole collection of weird, beautiful, addictive web experiments. Spend an hour.",
        "alternative_uses": ["Procrastination", "Sharing with friends", "Inspiration for devs"],
        "download_url": "https://neal.fun/",
        "homepage_url": "https://neal.fun/",
        "icon": "Rocket",
        "popularity": 79,
        "platforms": ["Web"],
    },
]


CURATED_REPOS = [
    {
        "name": "PowerToys",
        "full_name": "microsoft/PowerToys",
        "description": "Windows system utilities to maximize productivity.",
        "url": "https://github.com/microsoft/PowerToys",
        "stars": "112k",
        "language": "C#",
        "tags": ["windows", "utilities", "productivity"],
    },
    {
        "name": "stable-diffusion-webui",
        "full_name": "AUTOMATIC1111/stable-diffusion-webui",
        "description": "Web UI for Stable Diffusion image generation.",
        "url": "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
        "stars": "145k",
        "language": "Python",
        "tags": ["ai", "image-generation"],
    },
    {
        "name": "ohmyzsh",
        "full_name": "ohmyzsh/ohmyzsh",
        "description": "A delightful community-driven framework for managing your zsh configuration.",
        "url": "https://github.com/ohmyzsh/ohmyzsh",
        "stars": "175k",
        "language": "Shell",
        "tags": ["shell", "terminal", "themes"],
    },
    {
        "name": "public-apis",
        "full_name": "public-apis/public-apis",
        "description": "A collective list of free APIs for use in software and web development.",
        "url": "https://github.com/public-apis/public-apis",
        "stars": "315k",
        "language": "Python",
        "tags": ["api", "resources"],
    },
    {
        "name": "transformers",
        "full_name": "huggingface/transformers",
        "description": "State-of-the-art machine learning for PyTorch, TensorFlow, and JAX.",
        "url": "https://github.com/huggingface/transformers",
        "stars": "135k",
        "language": "Python",
        "tags": ["ai", "ml", "nlp"],
    },
    {
        "name": "llama.cpp",
        "full_name": "ggerganov/llama.cpp",
        "description": "Port of Facebook's LLaMA model in C/C++. Run LLMs on a laptop.",
        "url": "https://github.com/ggerganov/llama.cpp",
        "stars": "70k",
        "language": "C++",
        "tags": ["ai", "llm", "local"],
    },
    {
        "name": "terminal",
        "full_name": "microsoft/terminal",
        "description": "The new Windows Terminal and the original Windows console host.",
        "url": "https://github.com/microsoft/terminal",
        "stars": "95k",
        "language": "C++",
        "tags": ["terminal", "windows"],
    },
    {
        "name": "neovim",
        "full_name": "neovim/neovim",
        "description": "Vim-fork focused on extensibility and usability.",
        "url": "https://github.com/neovim/neovim",
        "stars": "82k",
        "language": "Vim Script",
        "tags": ["editor", "vim"],
    },
    {
        "name": "linux",
        "full_name": "torvalds/linux",
        "description": "Linux kernel source tree. The big one.",
        "url": "https://github.com/torvalds/linux",
        "stars": "170k",
        "language": "C",
        "tags": ["os", "kernel"],
    },
    {
        "name": "ComfyUI",
        "full_name": "comfyanonymous/ComfyUI",
        "description": "Most powerful and modular diffusion model GUI, API, and backend.",
        "url": "https://github.com/comfyanonymous/ComfyUI",
        "stars": "55k",
        "language": "Python",
        "tags": ["ai", "stable-diffusion"],
    },
    {
        "name": "awesome",
        "full_name": "sindresorhus/awesome",
        "description": "Awesome lists about all kinds of interesting topics.",
        "url": "https://github.com/sindresorhus/awesome",
        "stars": "320k",
        "language": "Markdown",
        "tags": ["resources", "lists"],
    },
    {
        "name": "FFmpeg",
        "full_name": "FFmpeg/FFmpeg",
        "description": "Mirror of https://git.ffmpeg.org/ffmpeg.git",
        "url": "https://github.com/FFmpeg/FFmpeg",
        "stars": "45k",
        "language": "C",
        "tags": ["video", "audio", "media"],
    },
]
